export const DEFAULT_REPORT_RULES = [
  {
    ruleId: 'et_g1_annual',
    name: 'Декларація ЄП (Група 1)',
    shortName: 'ЄП гр.1',
    category: 'unified_tax',
    frequency: 'annual',
    deadline: { type: 'fixed_date', month: 2, day: 28 },
    condition: { taxSystem: 'simplified', simplifiedGroup: [1], vatPayer: null, hasEmployees: null, exciseTax: null, landTax: null, environmentalTax: null, rentTax: null },
    active: true,
  },
  {
    ruleId: 'et_g2_annual',
    name: 'Декларація ЄП (Група 2)',
    shortName: 'ЄП гр.2',
    category: 'unified_tax',
    frequency: 'annual',
    deadline: { type: 'fixed_date', month: 2, day: 28 },
    condition: { taxSystem: 'simplified', simplifiedGroup: [2], vatPayer: null, hasEmployees: null, exciseTax: null, landTax: null, environmentalTax: null, rentTax: null },
    active: true,
  },
  {
    ruleId: 'et_g3_quarterly',
    name: 'Декларація ЄП (Група 3)',
    shortName: 'ЄП гр.3',
    category: 'unified_tax',
    frequency: 'quarterly',
    deadline: { type: 'days_after_period_end', value: 40 },
    condition: { taxSystem: 'simplified', simplifiedGroup: [3, '3vat'], vatPayer: null, hasEmployees: null, exciseTax: null, landTax: null, environmentalTax: null, rentTax: null },
    active: true,
  },
  {
    ruleId: 'vat_monthly',
    name: 'Декларація ПДВ',
    shortName: 'ПДВ',
    category: 'vat',
    frequency: 'monthly',
    deadline: { type: 'day_of_next_month', day: 20 },
    condition: { taxSystem: null, simplifiedGroup: null, vatPayer: true, hasEmployees: null, exciseTax: null, landTax: null, environmentalTax: null, rentTax: null },
    active: true,
  },
  {
    ruleId: 'income_annual',
    name: 'Декларація про майновий стан і доходи',
    shortName: 'ПДФО річна',
    category: 'income_tax',
    frequency: 'annual',
    deadline: { type: 'fixed_date', month: 5, day: 1 },
    condition: { taxSystem: 'general', simplifiedGroup: null, vatPayer: null, hasEmployees: null, exciseTax: null, landTax: null, environmentalTax: null, rentTax: null },
    active: true,
  },
  {
    ruleId: 'income_advance_q',
    name: 'Авансовий внесок ПДФО',
    shortName: 'ПДФО аванс',
    category: 'income_tax',
    frequency: 'fixed_dates',
    deadline: {
      type: 'fixed_dates',
      dates: [
        { month: 3, day: 15 },
        { month: 5, day: 15 },
        { month: 8, day: 15 },
        { month: 11, day: 15 },
      ],
    },
    condition: { taxSystem: 'general', simplifiedGroup: null, vatPayer: null, hasEmployees: null, exciseTax: null, landTax: null, environmentalTax: null, rentTax: null },
    active: true,
  },
  {
    ruleId: 'unified_report_legal_monthly',
    name: "Об'єднана звітність (ЄСВ + 4-ДФ) — юридичні",
    shortName: 'ЄСВ+4ДФ юр.',
    category: 'employees',
    frequency: 'monthly',
    deadline: { type: 'day_of_next_month', day: 20 },
    condition: { taxSystem: null, simplifiedGroup: null, clientType: 'legal', vatPayer: null, hasEmployees: true, exciseTax: null, landTax: null, environmentalTax: null, rentTax: null },
    active: true,
  },
  {
    ruleId: 'unified_report_fop_quarterly',
    name: "Об'єднана звітність (ЄСВ + 4-ДФ) — ФОП",
    shortName: 'ЄСВ+4ДФ ФОП',
    category: 'employees',
    frequency: 'quarterly',
    deadline: { type: 'days_after_period_end', value: 40 },
    condition: { taxSystem: null, simplifiedGroup: null, clientType: 'fop', vatPayer: null, hasEmployees: true, exciseTax: null, landTax: null, environmentalTax: null, rentTax: null },
    active: true,
  },
  {
    ruleId: 'excise_monthly',
    name: 'Декларація акцизного податку',
    shortName: 'Акциз',
    category: 'excise',
    frequency: 'monthly',
    deadline: { type: 'day_of_next_month', day: 20 },
    condition: { taxSystem: null, simplifiedGroup: null, vatPayer: null, hasEmployees: null, exciseTax: true, landTax: null, environmentalTax: null, rentTax: null },
    active: true,
  },
  {
    ruleId: 'land_annual',
    name: 'Декларація з плати за землю',
    shortName: 'Земля',
    category: 'land',
    frequency: 'annual',
    deadline: { type: 'fixed_date', month: 2, day: 20 },
    condition: { taxSystem: null, simplifiedGroup: null, vatPayer: null, hasEmployees: null, exciseTax: null, landTax: true, environmentalTax: null, rentTax: null },
    active: true,
  },
  {
    ruleId: 'env_quarterly',
    name: 'Декларація екологічного податку',
    shortName: 'Еко',
    category: 'environmental',
    frequency: 'quarterly',
    deadline: { type: 'days_after_period_end', value: 40 },
    condition: { taxSystem: null, simplifiedGroup: null, vatPayer: null, hasEmployees: null, exciseTax: null, landTax: null, environmentalTax: true, rentTax: null },
    active: true,
  },
  {
    ruleId: 'rent_quarterly',
    name: 'Декларація рентної плати',
    shortName: 'Рента',
    category: 'rent',
    frequency: 'quarterly',
    deadline: { type: 'days_after_period_end', value: 40 },
    condition: { taxSystem: null, simplifiedGroup: null, vatPayer: null, hasEmployees: null, exciseTax: null, landTax: null, environmentalTax: null, rentTax: true },
    active: true,
  },
]
